import React from "react";
import {
  ChevronDownIcon,
  SuppliersIcon,
  ContactsIcon,
  LocationIcon,
  ClientsIcon,
  WorkerIcon,
  SearchIcon,
  CloseIcon,
  SitesIcon,
  UsersIcon,
  PhoneIcon,
  TrashIcon,
  MenuIcon,
  EditIcon,
  InfoIcon,
  TickIcon,
  MailIcon,
  MobileIcon,
  ChevronUpDownIcon,
  PanIcon,
  AadhaarIcon,
  GstIcon,
} from "../../../lib";

const icons = [
  { name: "ClientsIcon", icon: <ClientsIcon /> },
  { name: "ContactsIcon", icon: <ContactsIcon /> },
  { name: "WorkerIcon", icon: <WorkerIcon /> },
  { name: "CloseIcon", icon: <CloseIcon /> },
  { name: "SitesIcon", icon: <SitesIcon /> },
  { name: "SuppliersIcon", icon: <SuppliersIcon /> },
  { name: "UsersIcon", icon: <UsersIcon /> },
  { name: "MenuIcon", icon: <MenuIcon /> },
  { name: "EditIcon", icon: <EditIcon /> },
  { name: "PhoneIcon", icon: <PhoneIcon /> },
  { name: "InfoIcon", icon: <InfoIcon /> },
  { name: "SearchIcon", icon: <SearchIcon /> },
  { name: "ChevronDownIcon", icon: <ChevronDownIcon /> },
  { name: "TickIcon", icon: <TickIcon /> },
  { name: "TrashIcon", icon: <TrashIcon /> },
  { name: "MailIcon", icon: <MailIcon /> },
  { name: "LocationIcon", icon: <LocationIcon /> },
  { name: "MobileIcon", icon: <MobileIcon /> },
  { name: "ChevronUpDownIcon", icon: <ChevronUpDownIcon /> },
  { name: "PanIcon", icon: <PanIcon /> },
  { name: "AadhaarIcon", icon: <AadhaarIcon /> },
  { name: "GstIcon", icon: <GstIcon /> },
];

export { icons };
